

service: weather-info 

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    GEOCODE_URL: "https://maps.googleapis.com/maps/api/geocode/json?address="
    GEOCODE_API_KEY: "AIzaSyAtIw3ao6Sd_kRKlQz0_WGLRaJL-wDJ_zs"
# you can define service wide environment variables here

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: false   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
plugins:
  - serverless-offline
  - serverless-webpack
# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  getWeatherInfo:
    handler: handler.getWeatherInfo
    events:
      - http:
          path: /weather
          method: get
          request:
            template:
              application/json: '{"zipcode" : "$input.params(''zipcode'')"}'

